### ISSUE TITLE
Monorepo Readme

### ISSUE THREAD

**Issue by srtfisher** [alleyinteractive/alley-scripts#21]
# User Story

> As a developer working on Alley Scripts, I want better documentation on what the repo is, how to work with it, how to make new releases, etc.

# Acceptance Criteria

- Update the README in the root of the project to follow Alley's standard README and fill out all details.
- Ensure that instructions on how to add and manage packages using Turbo is included.
- Ensure that instructions on how to cut a new release are included (by bumping the version number of a package, which autodeploys).

**Comment by stevenslack** [comment]
#623 changes included the following:
- Updated README in the root of the project following Alley's standard README.
- README instructions on how to add and manage packages using Turbo is included.
- README instructions on how to cut a new release with changeset
