### ISSUE TITLE
Replace @wordpress/element with React Packages

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/alley-scripts#474]
### Description

Per https://developer.wordpress.org/news/2023/11/whats-new-for-developers-november-2023/#move-away-from-wordpress-element-to-react the core team has shifted away from referencing the `@wordpress/element` wrapper in favor of referencing React/ReactDOM/etc directly. We should do the same.

# Acceptance Criteria

- Replace all references to `@wordpress/element` with references to React at the proper version for WordPress 6.4.

### Use Case

> As a package maintainer, I want to keep current with WordPress standards for working with Gutenberg.

**Comment by stevenslack** [comment]
Addressed in [@alleyinteractive/block-editor-tools@0.7.0](https://github.com/alleyinteractive/alley-scripts/releases/tag/%40alleyinteractive/block-editor-tools%400.7.0)
