### ISSUE TITLE
Add Support for node 20 and npm 10

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/alley-scripts#502]
### Description

Now that node 20 has gone LTS, and npm 10 is bundled with both node 18 and node 20, we should support both explicitly.

### Use Case

> As a developer, I want to be able to use these packages in a project that is using node 20 and/or npm 10.

### Acceptance Criteria

- Bump the version of node to 20 and npm to 10 in our tests
- Modify package.json files to explicitly declare support for node 20 and npm 10
- Cut new releases as necessary (e.g., block-editor-tools)

**Comment by benpbolton** [comment]
@kevinfodness the 'new releases as necessary' uses an example of `block-editor-tools`, however that specific project already [looks to be](https://github.com/alleyinteractive/alley-scripts/blob/main/packages/block-editor-tools/package.json#L13) happy with node 20/npm 10... was this just an example of a `package` or would a new release be necessary here and I'm overlooking something obvious?

**Comment by kevinfodness** [comment]
The package.json for alley-scripts was updated to support node 20 and npm 10 by modifying the engines to support > node 16 and > npm 8, yes, but the parent package.json requires node < 19. CI is using node 18 for tests/build/etc.

We should update this package to use node 20 and npm 10 in CI tests and as part of build/release while allowing support for node 16-20 in engines.

**Comment by srtfisher** [comment]
This was resolved via #531. For block-editor-tools, this was included in [0.6.0](https://github.com/alleyinteractive/alley-scripts/releases/tag/%40alleyinteractive%2Fblock-editor-tools%400.6.0).
