### ISSUE TITLE
usePostById Fatals if Post ID Does Not Exist

### ISSUE THREAD

**Issue by kevinfodness** [alleyinteractive/alley-scripts#543]
### Description of the bug

If a post ID is not found (either because it was deleted, or put in the trash, or reverted to draft) then `usePostById` will throw a `TypeError` and crash the script when attempting to set the cache (specifically, when trying to access the `subtype` property on something that is undefined).

### Steps To Reproduce

Call the `usePostById` with a post ID that doesn't exist and observe that the editor crashes.

### Additional Information

There is a TODO here that highlights the problem: https://github.com/alleyinteractive/alley-scripts/blob/main/packages/block-editor-tools/src/hooks/use-post-by-id/index.js#L32

### Acceptance Criteria

- Ensure that when a post ID is used in `usePostById` that does not exist or is in the trash or draft that the editor does not crash.
- Put a warning in the console that the post ID does not exist and that it is being skipped.

**Comment by theumee** [comment]
Hey Kevin, I have raised a PR. Can you check if it solves your issue?
