### ISSUE TITLE
Include Scheduled Posts in Post Picker

### ISSUE THREAD

**Issue by bmcnulty7** [alleyinteractive/alley-scripts#601]
### Description

Include scheduled posts in the post picker modal so editors can pick scheduled posts in various locations the post picker is used. A backfilled post should populate the post picker spot until the scheduled post goes live, then the scheduled post should appear in the selected location.

### Use Case

A user should be able to select a scheduled post from the post picker so that they don't need to wait until the post goes live to put it in the location they want it.

**Comment by mogmarsh** [comment]
I think this work is going to need to be done in the application using Post Picker and not in Post Picker itself. Post Picker supports passing additional parameters to the REST endpoint, but some server side filters will need to be added to return scheduled posts, and then the logic to backfill with a published post on the front end until the post is published will definitely be up to the parent application.

**Comment by anubisthejackle** [comment]
@mogmarsh Is there a technical hurdle that we'd need to leap for this? I know that the Post List component uses the Search API, and it doesn't seem that the Search API allows us to modify the statuses that are shown. If thats the only issue, then maybe we could modify it to use the Posts API instead?

**Comment by anubisthejackle** [comment]
It does seem like we could do this [client-side by filtering](https://github.com/WordPress/WordPress/blob/master/wp-includes/rest-api/search/class-wp-rest-post-search-handler.php#L93) `rest_post_search_query` and setting `$query_args['post_status'] = 'publish,future'`

**Comment by mogmarsh** [comment]
No changes need to be made to Post Picker. This will all need to be handled in the component calling Post Picker and also some server side filters.
